name: Run package unit tests

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Test ntm
      run: python tests/ntm.py
    - name: Test notify_me
      run: python tests/notify_me.py
  
